SELECT l1.patient_id, l2.GENERIC_FEATURE_NAME_grouplikeli FROM
((SELECT patient_id FROM CHOOSING_PATIENTS_EXPRESSION) l1
INNER JOIN
(SELECT t1.patient_id, LIKELI_FUNCTION AS GENERIC_FEATURE_NAME_grouplikeli FROM
((SELECT patient_id, FEATURE_NAMES_COMMA_SEPARATED FROM FEATURE_TABLE_NAME) t1
LIKELI_TABLES_FOR_JOIN)
GROUP BY t1.patient_id) l2
ON l1.patient_id = l2.patient_id);
