import os


INPUT_DIR = "../data/input"
OUTPUT_DIR = "../data/team/kohei/"


# Provided dataset
FILE_TRAIN_OUT = os.path.join(INPUT_DIR, "patients_train.csv")
FILE_TEST_OUT = os.path.join(INPUT_DIR, "patients_test.csv")
FILE_TRNEX_OUT = os.path.join(INPUT_DIR, "train_patients_to_exclude.csv")
FILE_TSTEX_OUT = os.path.join(INPUT_DIR, "test_patients_to_exclude.csv")
FILE_PA_OUT = os.path.join(INPUT_DIR, "patient_activity_head.csv")
FILE_PROC_OUT = os.path.join(INPUT_DIR, "procedure_head.csv")
FILE_PRES_OUT = os.path.join(INPUT_DIR, "prescription_head.csv")
FILE_SURG_OUT = os.path.join(INPUT_DIR, "surgical_head.csv")
FILE_DIAG_OUT = os.path.join(INPUT_DIR, "diagnosis_head.csv")
FILE_DIAG_CD = os.path.join(INPUT_DIR, "diagnosis_code.csv")
FILE_SURG_CD = os.path.join(INPUT_DIR, "surgical_code.csv")
FILE_PROC_CD = os.path.join(INPUT_DIR, "procedure_code.csv")
FILE_PHYS = os.path.join(INPUT_DIR, "physicians.csv")
FILE_DRUG = os.path.join(INPUT_DIR, "drugs.csv")

# Dmitry's files
FILE_DMITRY_CV_IDX = os.path.join(INPUT_DIR, "train_cv.csv")

# Output files (generated by kohei_v52.py)
MODEL_META_FILE = os.path.join(OUTPUT_DIR, "v52a_val.meta")
MODEL_META_FOLD_FILE = os.path.join(OUTPUT_DIR, "v52a_val_fold{}.meta")
CV_PRED_FILE = os.path.join(OUTPUT_DIR, "v52a_val")
CV_PRED_FOLD_FILE = os.path.join(OUTPUT_DIR, "v52a_val_fold{}")
TEST_PRED_FILE = os.path.join(OUTPUT_DIR, "v52a_test")
TEST_PRED_FOLD_FILE = os.path.join(OUTPUT_DIR, "v52a_test_fold{}")

# Kohei's extra feature set (generated by gen_feat2.py)
FILE_MISSING_CLAIM_PROC2 = os.path.join(
    OUTPUT_DIR,
    "{source:s}_num_removed_claim_proc_via_surg.csv")
